language: python

python:
  - 3.7

before_install:
  - pip install codecov nose2 nose2-cov

install:
  - pip install -r requirements.txt

script:
  - nose2 -F -C --coverage-report=term-missing -v

after_success:
  - codecov
